### ISSUE TITLE
Planning for CRAN 2.4-0 release

### ISSUE THREAD

**Issue by vincentvanhees** [wadpac/GGIR#424]
Given #423, I would like to make a new CRAN release before 8th of June.

Time plan:

**May 10-19:**
- [x] Add fixes to issue #423 to PR #422
- [x] Wait for feedback on PR #422 from @jhmigueles and/or @m-patterson. I hope at least one of you has time to do this before 21st of May?
- [x] Merge PR #422 in Master branch
- [x] Check out new PR #426 by Jairo and if all is good, merge that first.
- [x] Create GitHub-only release version 2.3-3
- [x] E-mail GGIR list to ask users to try out the version 2.3-3 and report urgent issues.

**May 20-29:**
- [x] Check GGIR for new R 4.1 release.
- [ ] Consider creating a 2.3-4 release if there are any significant changes before the 2.4-0 release.
- [x] Fix urgent issues, if any.

**May 30 - June 3:**
- [x] Prepare and submit 2.4-0 release to CRAN

**Comment by vincentvanhees** [comment]
... I got the version numbers wrong, now corrected.

**Comment by jhmigueles** [comment]
Hi Vincent,

I’ve been working on a tiny bug related to g.report.part2 this morning (see https://github.com/wadpac/GGIR/issues/425 and the branch https://github.com/wadpac/GGIR/tree/issue425_reportpart2stops). I’m not sure if I should do the pull request now or wait until you merge your branch on the fragmentation metrics with the master. I think we can include this one in the new release as well, what do you think?

**Comment by vincentvanhees** [comment]
Hi Jairo, Feel free to make a separate pull request, we can merge them, no problem.
Yes, it would be good to include in this in the new release. Thanks

**Comment by vincentvanhees** [comment]
I have now submitted 2.4-0 to CRAN, once it has been accepted by CRAN later this week I will also create 2.4-0 release here on GitHub.
